### ISSUE TITLE
alpine

### ISSUE THREAD

**Issue by Neftedollar** [fsprojects/docker-fsharp#10]
Is it posible to use alpine? It's not so big as ubuntu.

**Comment by haf** [comment]
Yes, but you need to verify that MUSL C-bindings work well with mono and with F#, which I haven't had time to do. If you want, I'd be open to providing an alternative build if you can verify functionality first.

**Comment by Neftedollar** [comment]
@haf  I use docker-alpine with mono(c#) in production. For automama.ru fo example. 
Didn't use it with fsharp. But I'll fix it soon.

**Comment by haf** [comment]
Yes, indeed, that needs fixing ASAP! ;)

**Comment by haf** [comment]
Closing due to lack of action.
