### ISSUE TITLE
Merge the multiple ENV commands to fewer to reduce the number of layers

### ISSUE THREAD

**Issue by mastoj** [fsprojects/docker-fsharp#11]
You can put multiple `ENV` on the same line, and I think it is good practice to reduce the number of layers. 

I'm thinking of something like:

```
ENV FSHARP_VERSION 4.0.0.4
ENV FSHARP_PREFIX=/usr \
    FSHARP_GACDIR=/usr/lib/mono/gac \
    FSHARP_BASENAME=fsharp-$FSHARP_VERSION \
    FSHARP_ARCHIVE=$FSHARP_VERSION.tar.gz \
    FSHARP_ARCHIVE_URL=https://github.com/fsharp/fsharp/archive/$FSHARP_VERSION.tar.gz
```

Make sense?

**Comment by haf** [comment]
Sure. Go ahead and PR.

**Comment by mastoj** [comment]
@haf I have an updated version that brings the number of layers down to 5 from 13. However, I had to re-add the `--force-yes` to build the image and that feels weird since that was the last thing you removed.

**Comment by haf** [comment]
That's fine, it's a progression of changes; to target what's 'optimal'.
