### ISSUE TITLE
Can't see what I'm typing

### ISSUE THREAD

**Issue by nojaf** [fsprojects/docker-fsharp#15]
When I run ```docker run --rm -i fsharp/fsharp``` on Docker for Windows Beta I can't see what I'm typing in the REPL. When I hit enter, the output is shown in the REPL though.

**Comment by mausch** [comment]
Try `-t` to allocate a tty:

`docker run --rm -it fsharp/fsharp`

**Comment by nojaf** [comment]
Works indeed! However I'm still unable to see ```printfn``` statements.

**Comment by mausch** [comment]
Hmm, looks like an issue with Docker for Windows? Works for me on Ubuntu 14

```
$ docker run --rm -it fsharp/fsharp

F# Interactive for F# 4.0 (Open Source Edition)
Freely distributed under the Apache 2.0 Open Source License

For help type #help;;

> printfn "qwe";;
qwe
val it : unit = ()
```

**Comment by nojaf** [comment]
Turns out the problem was between the keyboard and the screen, I forget to end my statements with ```;;```

**Comment by haf** [comment]
;)
