### ISSUE TITLE
Should the container run fsharpi?

### ISSUE THREAD

**Issue by dsyme** [fsprojects/docker-fsharp#2]
See comment here.  

    https://github.com/fsprojects/docker-fsharp/commit/fd42c0b358bb6af877ebcf8013379cd084ad9983#commitcomment-14212725

> I'm using the fsharp/fsharp docker image for the first time.  It feels to me that perhaps this particular image should be called  fsharp/fsharpi  or  fsharp/fsharp-script ? I'm new to Docker but I somehow expected  fsharp/fsharp  to be a base dev image containing the F# compiler. How does this compare to other images for other languages with compilers?

**Comment by martintrojer** [comment]
I totally agree with @dsyme 

IMHO the fsharp/fsharp container should contain all fsharp tools needed to develop and build fsharp applications. You should also be able to base your production application on this image (by using either fsx or pre-compiled .exes).

Good examples;

* https://hub.docker.com/_/golang/
* https://hub.docker.com/_/node/

**Comment by dsyme** [comment]
The Node containers do start node in a similar way so I see why it is doing this: https://github.com/nodejs/docker-node/blob/2445743c1453941f787b0aa22cca51c62a1a3f09/5.0/wheezy/Dockerfile

I believe the idea is to change the command run on startup or derive from the container?  

The fsharp/fsharp container does contain xbuild and nuget.  It doesn't contain paket or FAKE.

**Comment by dsyme** [comment]
I'm actually going to close this since following the example of node does seem to make sense.

**Comment by haf** [comment]
@dsyme  Yes, it's all modeled very similar to other languages' containers... And as you say, you can just override the command, like is the best-practice when building official docker containers.

I've yet to add an ONBUILD stanza in the dockerfile and to create many different tags.

Also, mono 4.0.4 is a non-functional mono for F# so that also needs to be fixed.
