### ISSUE TITLE
fsharp/fsharp:latest not found by Bitbucket pipelines

### ISSUE THREAD

**Issue by stevenranney** [fsprojects/docker-fsharp#20]
Admittedly, I'm new to Bitbucket and their pipelines (and I know that this isn't Bitbucket).  However, my F# console app built successfully until four days ago which, coincidentally is also when a number of pushes were made to the repo here.

I use the [`fsharp:latest` image from hub.docker.com](https://hub.docker.com/_/fsharp/) but the build fails because of the error: 

`Error: image fsharp/fsharp:latest not found`

Any ideas what may be going on?  

Again, everything built successfully until four days ago when I started getting these failures.

**Comment by haf** [comment]
Use `FROM fsharp:latest`

**Comment by haf** [comment]
BTW, you actually mention that in your message. Look closely! It's **not** `fsharp/fsharp:latest` but `fsharp:latest`.

**Comment by stevenranney** [comment]
Turns out that Docker was having big issues yesterday too.  So, even with the correct line of `fsharp:latest`, builds were failing all over the place.  It wasn't just me!

**Comment by haf** [comment]
S3 has tentacles everywhere.
