### ISSUE TITLE
paket hangs when using this as a base image

### ISSUE THREAD

**Issue by jackmott** [fsprojects/docker-fsharp#37]
I have a small project for which `paket install` runs fine and quickly, but when running it under Docker it hangs.  The hang occurs when using paket install, or paket restore.  While hung the CPU is working like crazy, under the mono process.

When using paket restore --verbose, the last output before hanging it "Parsing paket.dependencies"

my paket.dependencies file is:
```
source https://api.nuget.org/v3/index.json
framework >= net45

nuget DotLiquid
nuget FSharp.Data
nuget FsSql
nuget MathNet.Numerics.FSharp
nuget Newtonsoft.Json
nuget Npgsql = 3.1
nuget Octokit
nuget SQLProvider
nuget Suave >= 2.3.0-beta3
nuget Suave.DotLiquid >= 2.3.0-beta3
nuget Suave.Experimental >= 2.3.0-beta3
```

my Dockerfile is:
```
FROM fsharp:latest
ADD . /
WORKDIR /
RUN mono .paket/paket.bootstrapper.exe
RUN mono .paket/paket.exe restore --verbose
RUN ./build.sh
ENTRYPOINT ["mono","/root/AlphaFront/bin/Release/AlphaFront.exe"]
```
I run the dockerfile with a github repo as the context.

I am not sure if this is a problem with paket, or the base image, or none of the above!

**Comment by stevedesmond-ca** [comment]
It looks like this is an issue with either paket or mono -- running it verbosely:
```
root@ddde73d59c57:/# mono .paket/paket.exe init -v
Paket version 5.153.0
Paket is already initialized in /
found: /paket.dependencies
Parsing /paket.dependencies
```
Which is where it hangs.

Can you confirm that the versions of mono and paket you're using are working fine outside of the Docker container?

**Comment by jackmott** [comment]
Yes can confirm it works fine with the same versions outside of the Docker container.  Also, it happens with older versions of both paket, and mono as well. Using the :4.0 tag on the base image, same problem, older paket, same problem. According to the people over on the paket repo, it is a long known problem but they have no idea why.

**Comment by dsyme** [comment]
Closing as this is archived, use one of these instead:

* [microsoft-dotnet](https://hub.docker.com/_/microsoft-dotnet) 
* [mono](https://hub.docker.com/_/mono)
