### ISSUE TITLE
Use Mono 4.2

### ISSUE THREAD

**Issue by haf** [fsprojects/docker-fsharp#4]
4.0.4 is a very buggy release, and F# doesn't work well with it.

We need to find a way to fetch pre-stable mono releases. Perhaps they've pushed pre-stable releases now, or perhaps they haven't (like when I last checked).

**Comment by naveensrinivasan** [comment]
The mono 4.2 is available in the alpha channel http://www.mono-project.com/docs/getting-started/install/linux/#debian-ubuntu-and-derivatives-alpha-channel. Based on the alpha I was able to create a Dockerfile https://github.com/naveensrinivasan/fsharp-docker


Would you want to wait until it get's out of the alpha?

**Comment by dsyme** [comment]
I'd prefer if we upgraded the default docker base to 4.2 right away (though we should likely have a whole range of tags for different mono bases so users can choose?)

**Comment by TheAngryByrd** [comment]
https://github.com/mono/docker has good examples of multiple versions of mono in a debian:wheezy container.  Does it make sense to offer multiple linux flavors as well?

**Comment by haf** [comment]
I agree; currently testing the PR #5 locally. I also think LibUV is a good default install to include, because you can then use it to run the F# web server Suave; do you agree?

**Comment by TheAngryByrd** [comment]
IMO, it shouldn't be part of the main image, that's what Docker's layering is supposed to be for. Build images on other images. (http://tuhrig.de/layering-of-docker-images/)  

So we theoretically could have a Fsharp image, then the Suave/LibUV image references the fsharp image.  And so if another project just needed the Fsharp image, it wouldn't have the extra unnecessary dependencies.

**Comment by naveensrinivasan** [comment]
I agree wiith @TheAngryByrd it shouldn't be the default one. :+1:
