### ISSUE TITLE
Consider deprecating this library in favor of recommending "official" images

### ISSUE THREAD

**Issue by stevedesmond-ca** [fsprojects/docker-fsharp#56]
A lot has happened in the .NET world over the past several years, and Docker is now a first-class citizen. Are these images superfluous now that one can run `dotnet fsi` and `fsharpi` from the `microsoft/dotnet` and `mono` images respectively?

**Comment by CodeMan99** [comment]
I am new to both docker and dotnet. Would you mind verifying the resources below?

* [ ] [microsoft-dotnet](https://hub.docker.com/_/microsoft-dotnet) - See "Featured Repos" section.
* [ ] [mono](https://hub.docker.com/_/mono)

**Comment by dsyme** [comment]
> Are these images superfluous now that one can run dotnet fsi and fsharpi from the microsoft/dotnet and mono images respectively?

Yes they are superfluous

**Comment by dsyme** [comment]
I've added a note to the README that this is now archived

**Comment by dsyme** [comment]
Thanks!
