### ISSUE TITLE
.NET 5 Version

### ISSUE THREAD

**Issue by TheDevKnight** [fsprojects/docker-fsharp#57]
Hi,

will there by a .NET 5 version of the docker Image?

Regards

**Comment by dsyme** [comment]
Any docker image with the .NET SDK now contains F# support.  THere is no need for a separate F# docker image

**Comment by TheDevKnight** [comment]
Hi @dsyme, 

Thank you for the hint. And the FSI is also available in in .Net 5 Docker Images? Runtime or SDK version?

Regards

**Comment by TheDevKnight** [comment]
OK, 

could answer the question by myself :) 

For all who want to start the FSI direct in the container. Big difference is, that the powershell core (pwsh) is installed and not bash.

`docker run -i mcr.microsoft.com/dotnet/sdk pwsh -c "dotnet fsi"` 

Regards
