### ISSUE TITLE
Tag names aren't consitent

### ISSUE THREAD

**Issue by naveensrinivasan** [fsprojects/docker-fsharp#6]
The tag names in the docker hub aren't consitent

https://hub.docker.com/r/fsharp/fsharp/tags/

>4.0.0.4
>v4.0	

IMO it shouldn't be prefixed with v4.0.

**Comment by haf** [comment]
Ok, you're probably right, thanks. Leaving open till fix.

**Comment by haf** [comment]
Done, deleted v4.0.
